baseURL = "/"
languageCode = "en-us"
title = "SourceBans++"
theme = "kube"
description = "Global admin, ban, and communication management system for the Source engine"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "RumbleFrog" # add your company name
  github = "RumbleFrog" # add your github profile name
  twitter = "RumbleFrog_" # add your twitter profile
  email = "rumblefrog@protonmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
        name = "Blog"
        weight = -100
        url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
