baseURL = "/"
languageCode = "en-us"
title = "SourceBans++"
theme = "kube"
description = "Global admin, ban, and communication management system for the Source engine"
Paginate = 4
googleAnalytics = "UA-68577666-5"
[Params]
  RSSLink = "/index.xml"
  author = "SourceBans++" # add your company name
  github = "sbpp" # add your github profile name
  twitter = "RumbleFrog_" # add your twitter profile
  email = "rumblefrog@protonmail.com"
[Params.seo.webmaster_verifications]
  google = "NMu_qHiZPOvLzW1_DvAKrQfdQUAOdKxGnjbI8oa0cGo"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
        name = "Blog"
        weight = -100
        url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "/faq/"
